name: main
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.6'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        cd tests
        python3 -m pytest --cov-report xml --cov project
        mv coverage.xml ../
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
